# Generated by Django 3.1.1 on 2020-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents_Details_Model',
            fields=[
                ('SNO', models.AutoField(primary_key=True, serialize=False)),
                ('ID', models.IntegerField(unique=True)),
                ('NAME', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=200)),
                ('CITY', models.CharField(max_length=100)),
                ('ZIPCODE', models.IntegerField()),
                ('STATE', models.CharField(max_length=100)),
            ],
        ),
    ]
